spring:
  application:
    name: greeting-service

management:
  endpoints:
    web:
      exposure:
        include:
        - refresh

greeting-service:
  greeting: "Hello"
  default-value: "World"
